[package]
name = "efm32pg1b-hal"
version = "0.1.0"
authors = ["Bogdan Olar <olar.bogdan.dev@gmail.com>"]
edition = "2018"
description = "Hardware abstraction layer (HAL) for Silicon Labs EFM32PG1B microcontrollers"
keywords = ["embedded-hal", "efm32", "efm32pg1b", "hal", "silabs"]
categories = ["embedded", "hardware-support", "no-std"]
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/BogdanOlar/efm32pg1b-hal"

[dependencies]
efm32pg1b-pac = { git = "https://github.com/BogdanOlar/efm32pg1b-pac" }
embedded-hal = { version = "0.2.3", features = ["unproven"] }
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"

# Uncomment for the panic example.
# panic-itm = "0.4.1"

# Uncomment for the allocator example.
# alloc-cortex-m = "0.4.0"

# Uncomment for the device example.
# Update `memory.x`, set target to `thumbv7em-none-eabihf` in `.cargo/config`,
# and then use `cargo build --examples device` to build it.
# [dependencies.stm32f3]
# features = ["stm32f303", "rt"]
# version = "0.7.1"

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
